from __future__ import annotations

from typing import Dict, List


RULES: List[Dict[str, object]] = [
    # ─── ANEMIA SUBTYPES ────────────────────────────────────────────────────────
    {
        "id": "microcytic_hypochromic_anemia",
        "name": "Microcytic Hypochromic Anemia",
        "severity": "moderate",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "mcv", "status": "low"},
            {"metric": "mchc", "status": "low"},
        ],
        "explanation": "Low hemoglobin with low MCV and low MCHC — small, pale red cells carrying less hemoglobin than normal.",
        "simple_explanation": "Your red blood cells are smaller and paler than normal, which usually means iron deficiency or thalassemia trait.",
        "possible_causes": [
            "Iron deficiency anemia (most common cause)",
            "Thalassemia trait",
            "Chronic blood loss (GI bleed, heavy periods)",
            "Anemia of chronic disease (sometimes)",
        ],
        "actions": [
            "Ask your doctor for iron studies: serum ferritin, serum iron, TIBC.",
            "Consider thalassemia screening if iron studies are normal.",
            "Increase dietary iron: red meat, spinach, lentils, dates, fortified cereals.",
            "Vitamin C with iron-rich meals improves absorption.",
            "Avoid tea/coffee immediately after meals if iron-deficient.",
        ],
    },
    {
        "id": "microcytic_anemia",
        "name": "Microcytic Anemia",
        "severity": "moderate",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "mcv", "status": "low"},
        ],
        "explanation": "Low hemoglobin with low MCV suggests smaller-than-normal red blood cells.",
        "simple_explanation": "Your red blood cells are smaller than normal and may carry less oxygen — iron deficiency is the most likely cause.",
        "possible_causes": [
            "Iron deficiency",
            "Chronic blood loss",
            "Thalassemia trait",
            "Longstanding nutritional deficiency",
        ],
        "actions": [
            "Consult a doctor for a full anemia workup including ferritin and iron studies.",
            "Ask whether thalassemia screening is appropriate.",
            "Improve iron-rich intake: spinach, dates, beans, red meat.",
            "Take iron supplements only as prescribed.",
        ],
    },
    {
        "id": "normocytic_anemia",
        "name": "Normocytic Anemia",
        "severity": "moderate",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "mcv", "status": "normal"},
        ],
        "explanation": "Low hemoglobin with normal-sized red blood cells — anemia without a size change.",
        "simple_explanation": "Your blood is carrying less oxygen but the red cells look normal in size. This is often from blood loss, chronic illness, or kidney disease.",
        "possible_causes": [
            "Anemia of chronic disease or inflammation",
            "Acute blood loss",
            "Renal (kidney) disease reducing erythropoietin",
            "Hypothyroidism",
            "Early iron or B12/folate deficiency",
            "Hemolysis (red cell destruction)",
        ],
        "actions": [
            "Check kidney function (creatinine, eGFR) and thyroid (TSH).",
            "Review symptoms: fatigue, shortness of breath, dizziness.",
            "Ask about any chronic conditions or medications.",
            "Discuss whether a reticulocyte count and peripheral smear are needed.",
        ],
    },
    {
        "id": "macrocytic_anemia",
        "name": "Macrocytic Anemia",
        "severity": "moderate",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "mcv", "status": "high"},
        ],
        "explanation": "Low hemoglobin with large red blood cells — the cells are oversized and function poorly.",
        "simple_explanation": "Your red blood cells are bigger than normal, which often points to a B12 or folate deficiency.",
        "possible_causes": [
            "Vitamin B12 deficiency",
            "Folate (B9) deficiency",
            "Liver disease or alcohol use",
            "Hypothyroidism",
            "Certain medications (methotrexate, hydroxyurea)",
        ],
        "actions": [
            "Ask your doctor to test serum B12 and folate levels.",
            "Review alcohol intake and liver function.",
            "Check thyroid function (TSH).",
            "Dietary sources of B12: eggs, dairy, meat, fish.",
            "Dietary sources of folate: leafy greens, legumes, fortified grains.",
        ],
    },
    {
        "id": "severe_anemia",
        "name": "Severe Anemia",
        "severity": "significant",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "rbc", "status": "low"},
            {"metric": "hematocrit", "status": "low"},
        ],
        "explanation": "Low hemoglobin, low RBC count, and low hematocrit together indicate significant reduction in red cell mass.",
        "simple_explanation": "Your blood is significantly lacking in red blood cells across multiple measures. This needs prompt medical evaluation.",
        "possible_causes": [
            "Severe iron, B12, or folate deficiency",
            "Significant blood loss",
            "Bone marrow failure or suppression",
            "Hemolytic anemia",
            "Aplastic anemia",
        ],
        "actions": [
            "Seek medical evaluation promptly — do not delay.",
            "Comprehensive workup: iron studies, B12, folate, reticulocyte count, peripheral smear.",
            "Discuss whether further investigation (bone marrow) is warranted.",
            "Avoid strenuous physical activity until assessed.",
        ],
    },

    # ─── POLYCYTHEMIA / HIGH RBC ─────────────────────────────────────────────
    {
        "id": "polycythemia_pattern",
        "name": "Polycythemia Pattern",
        "severity": "moderate",
        "conditions": [
            {"metric": "hemoglobin", "status": "high"},
            {"metric": "hematocrit", "status": "high"},
        ],
        "explanation": "Elevated hemoglobin and hematocrit suggest an increased red blood cell mass, which thickens the blood.",
        "simple_explanation": "Your blood has too many red cells, making it thicker than normal. This can be a normal response to altitude/dehydration, or rarely a bone marrow condition.",
        "possible_causes": [
            "Dehydration (most common, benign)",
            "Chronic low oxygen (smoking, high altitude, lung disease)",
            "Polycythemia vera (rare bone marrow disorder)",
            "Sleep apnea",
        ],
        "actions": [
            "Ensure adequate hydration and retest.",
            "If you smoke, discuss cessation with your doctor.",
            "If values remain high after hydration, see a doctor for JAK2 mutation testing.",
            "Evaluate for sleep apnea or chronic lung disease if relevant.",
        ],
    },

    # ─── WHITE CELL PATTERNS ─────────────────────────────────────────────────
    {
        "id": "leukocytosis_bacterial",
        "name": "Leukocytosis with Neutrophilia",
        "severity": "moderate",
        "conditions": [
            {"metric": "wbc", "status": "high"},
            {"metric": "neutrophils", "status": "high"},
        ],
        "explanation": "High WBC count driven by elevated neutrophils — the classic bacterial infection or severe stress pattern.",
        "simple_explanation": "Your white blood cell count is high, especially the neutrophils. This is your immune system's typical response to a bacterial infection or significant physical stress.",
        "possible_causes": [
            "Bacterial infection (common: UTI, pneumonia, skin/soft tissue)",
            "Physical or physiological stress (surgery, trauma)",
            "Corticosteroid use",
            "Inflammatory conditions (rheumatoid arthritis, IBD)",
            "Rarely: leukemia or bone marrow disorder",
        ],
        "actions": [
            "Look for signs of infection: fever, pain, cough, urinary symptoms.",
            "Review any medications — steroids cause neutrophilia.",
            "Repeat CBC in 1–2 weeks if no infection is found.",
            "See a doctor promptly if fever or localizing symptoms are present.",
        ],
    },
    {
        "id": "possible_infection",
        "name": "Leukocytosis",
        "severity": "mild",
        "conditions": [
            {"metric": "wbc", "status": "high"},
        ],
        "explanation": "An elevated white blood cell count can occur with infection, inflammation, or physiologic stress.",
        "simple_explanation": "Your immune cell count is higher than normal. This often means your body is fighting something — an infection, inflammation, or a recent physical stress.",
        "possible_causes": [
            "Recent infection",
            "Inflammation",
            "Physiologic stress or recent exercise",
            "Medication effect (steroids)",
        ],
        "actions": [
            "Check for fever, sore throat, cough, or urinary symptoms.",
            "Review the result with a doctor if symptoms are present or the count stays elevated.",
            "Repeat testing may be useful if advised clinically.",
        ],
    },
    {
        "id": "leukopenia",
        "name": "Leukopenia",
        "severity": "moderate",
        "conditions": [
            {"metric": "wbc", "status": "low"},
        ],
        "explanation": "A low white blood cell count reduces immune defense capacity.",
        "simple_explanation": "Your white blood cell count is lower than normal, which means your body's defenses against infection may be weakened.",
        "possible_causes": [
            "Viral infections (especially influenza, HIV, hepatitis)",
            "Bone marrow suppression from medications or chemotherapy",
            "Autoimmune conditions (lupus)",
            "Nutritional deficiencies (B12, folate, copper)",
            "Aplastic anemia",
        ],
        "actions": [
            "Seek medical evaluation, especially if count is very low.",
            "Avoid crowded places and sick contacts until reviewed.",
            "Tell your doctor about all medications and supplements.",
            "Ask about CBC repeat and bone marrow evaluation if low persists.",
        ],
    },
    {
        "id": "viral_pattern",
        "name": "Viral Lymphocytosis Pattern",
        "severity": "mild",
        "conditions": [
            {"metric": "lymphocytes", "status": "high"},
        ],
        "explanation": "A high lymphocyte percentage is a common response to viral infections.",
        "simple_explanation": "Your lymphocytes are elevated — this is typically how your immune system responds to a viral infection like the flu or a cold.",
        "possible_causes": [
            "Viral infection (EBV/mono, CMV, influenza, COVID-19)",
            "Recovery phase after viral illness",
            "Pertussis (whooping cough)",
            "Rarely: lymphocytic leukemia",
        ],
        "actions": [
            "Monitor for symptoms: sore throat, swollen glands, fatigue.",
            "If lymphocytes are very high (>5000/uL) or have been elevated for weeks, see a doctor.",
            "Rest, hydrate, and monitor if symptoms are mild.",
            "Consider monospot or EBV serology if symptoms suggest mononucleosis.",
        ],
    },
    {
        "id": "lymphopenia",
        "name": "Lymphopenia",
        "severity": "mild",
        "conditions": [
            {"metric": "lymphocytes", "status": "low"},
        ],
        "explanation": "Low lymphocyte percentage can indicate immune suppression or certain infections.",
        "simple_explanation": "Your lymphocyte count is lower than normal, which can mean your immune system is temporarily suppressed or stressed.",
        "possible_causes": [
            "Viral infections (HIV, COVID-19, influenza — early phase)",
            "Corticosteroid use",
            "Autoimmune conditions",
            "Malnutrition or zinc/protein deficiency",
            "Post-chemotherapy or radiation",
        ],
        "actions": [
            "Discuss with a doctor if lymphopenia is persistent.",
            "Ensure good nutrition and hydration.",
            "Review medications with your doctor.",
        ],
    },
    {
        "id": "eosinophilia",
        "name": "Eosinophilia",
        "severity": "mild",
        "conditions": [
            {"metric": "eosinophils", "status": "high"},
        ],
        "explanation": "Elevated eosinophils are a classic marker for allergic or parasitic conditions.",
        "simple_explanation": "Your eosinophil count is high. This is often a sign of an allergy, asthma, or a parasitic infection.",
        "possible_causes": [
            "Allergic conditions (asthma, eczema, hay fever, food allergy)",
            "Parasitic infections (especially intestinal worms)",
            "Drug hypersensitivity reactions",
            "Inflammatory bowel disease",
            "Rarely: hypereosinophilic syndrome",
        ],
        "actions": [
            "Review allergy history and current medications.",
            "Stool examination for ova and parasites if relevant.",
            "Skin prick testing or IgE panel if allergic cause is suspected.",
            "Discuss antiparasitic treatment with your doctor if parasite exposure is possible.",
        ],
    },
    {
        "id": "neutropenia",
        "name": "Neutropenia",
        "severity": "moderate",
        "conditions": [
            {"metric": "neutrophils", "status": "low"},
        ],
        "explanation": "Low neutrophil percentage increases susceptibility to bacterial infections.",
        "simple_explanation": "Your neutrophil count is low, meaning your main bacterial defense cells are reduced. You may be more vulnerable to infections.",
        "possible_causes": [
            "Viral infections (a common temporary cause)",
            "Medications (chemotherapy, certain antibiotics, antithyroid drugs)",
            "Autoimmune neutropenia",
            "Severe B12 or folate deficiency",
            "Bone marrow disorder",
        ],
        "actions": [
            "Avoid contact with sick individuals.",
            "See a doctor promptly if fever develops.",
            "Review all medications — drug-induced neutropenia is common.",
            "If severe or persistent, bone marrow evaluation may be needed.",
        ],
    },

    # ─── PLATELET PATTERNS ──────────────────────────────────────────────────
    {
        "id": "thrombocytopenia",
        "name": "Thrombocytopenia",
        "severity": "moderate",
        "conditions": [
            {"metric": "platelets", "status": "low"},
        ],
        "explanation": "Low platelet count impairs blood clotting and increases bleeding risk.",
        "simple_explanation": "Your platelet count is lower than normal, which means your blood may take longer to clot. Bruising easily or prolonged bleeding can occur.",
        "possible_causes": [
            "Immune Thrombocytopenia (ITP — immune system destroying platelets)",
            "Viral infections (dengue, HIV, hepatitis)",
            "Medications (heparin, certain antibiotics, NSAIDs)",
            "Bone marrow suppression",
            "Hypersplenism (enlarged spleen trapping platelets)",
            "Nutritional deficiency",
        ],
        "actions": [
            "Report unusual bruising, petechiae (tiny red dots on skin), or prolonged bleeding.",
            "Avoid aspirin and NSAIDs (ibuprofen) unless directed by a doctor.",
            "Seek medical review — the cause determines treatment.",
            "If platelet count is below 50,000, seek urgent evaluation.",
        ],
    },
    {
        "id": "thrombocytosis",
        "name": "Thrombocytosis",
        "severity": "mild",
        "conditions": [
            {"metric": "platelets", "status": "high"},
        ],
        "explanation": "High platelet count can be reactive (to infection/inflammation) or primary (bone marrow driven).",
        "simple_explanation": "Your platelet count is higher than normal. This is usually a reaction to infection or inflammation, but very high counts may need further investigation.",
        "possible_causes": [
            "Reactive thrombocytosis from infection or inflammation (most common)",
            "Iron deficiency anemia",
            "Post-splenectomy",
            "Essential thrombocythemia (rare bone marrow disorder)",
        ],
        "actions": [
            "If platelets are very high (>700,000), seek medical evaluation.",
            "Treat the underlying infection or inflammation if present.",
            "Repeat CBC after treatment to see if counts normalize.",
            "Ask about bone marrow workup if no reactive cause is found.",
        ],
    },
    {
        "id": "platelet_disorder",
        "name": "Platelet Count Abnormality",
        "severity": "moderate",
        "conditions_any": [
            {"metric": "platelets", "status": "low"},
            {"metric": "platelets", "status": "high"},
        ],
        "explanation": "The platelet count is outside the normal range.",
        "simple_explanation": "Platelets help your blood clot — a count outside the normal range may need follow-up depending on how far off it is.",
        "possible_causes": [
            "Infection or inflammation",
            "Iron deficiency",
            "Immune or bone marrow causes",
        ],
        "actions": [
            "Discuss bruising, bleeding, headaches, or clotting history with a doctor.",
            "Repeat CBC to confirm the finding.",
            "Seek medical advice sooner if there is active bleeding or unusual bruising.",
        ],
    },

    # ─── COMBINED / COMPLEX PATTERNS ─────────────────────────────────────────
    {
        "id": "pancytopenia",
        "name": "Pancytopenia Pattern",
        "severity": "significant",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "wbc", "status": "low"},
            {"metric": "platelets", "status": "low"},
        ],
        "explanation": "All three major cell lines are reduced — this is called pancytopenia and requires thorough investigation.",
        "simple_explanation": "Your red cells, white cells, and platelets are all low. This is a serious finding that needs prompt medical attention — it suggests the bone marrow may not be producing enough cells.",
        "possible_causes": [
            "Aplastic anemia (bone marrow failure)",
            "Myelodysplastic syndrome",
            "Vitamin B12 or folate deficiency (severe)",
            "Hypersplenism",
            "Bone marrow infiltration (leukemia, lymphoma, metastasis)",
            "Severe infection or sepsis",
        ],
        "actions": [
            "Seek prompt medical evaluation — do not delay.",
            "Expect a bone marrow biopsy and comprehensive blood workup.",
            "Avoid aspirin, NSAIDs, and contact sports until evaluated.",
            "Do not ignore symptoms: fatigue, fever, bruising, or infections.",
        ],
    },
    {
        "id": "dengue_pattern",
        "name": "Dengue-Like Pattern",
        "severity": "significant",
        "conditions": [
            {"metric": "wbc", "status": "low"},
            {"metric": "platelets", "status": "low"},
        ],
        "explanation": "Leukopenia combined with thrombocytopenia is a classic pattern seen in dengue fever and other viral hemorrhagic fevers.",
        "simple_explanation": "Both your white cells and platelets are low together — this combination is commonly seen in dengue fever, especially if you have had fever with body aches recently.",
        "possible_causes": [
            "Dengue fever",
            "Other viral hemorrhagic fevers",
            "Chikungunya",
            "Severe viral infections",
        ],
        "actions": [
            "If you have fever, body aches, rash, or eye pain — see a doctor immediately.",
            "Dengue NS1 antigen and IgM/IgG serology should be tested.",
            "Stay hydrated and monitor platelet trends closely.",
            "Avoid aspirin and NSAIDs — use paracetamol for fever only.",
            "Seek hospital admission if platelets drop below 50,000.",
        ],
    },
    {
        "id": "infection_with_anemia",
        "name": "Active Infection with Anemia",
        "severity": "moderate",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "wbc", "status": "high"},
        ],
        "explanation": "Low hemoglobin alongside elevated white cells suggests ongoing infection alongside existing or worsening anemia.",
        "simple_explanation": "Your body appears to be fighting an infection (high white cells) while also having low hemoglobin. Both need to be addressed.",
        "possible_causes": [
            "Bacterial infection complicating underlying anemia",
            "Anemia of chronic inflammation/disease",
            "Blood loss with reactive leukocytosis",
        ],
        "actions": [
            "Treat the infection first — anemia may partially improve after.",
            "Review hemoglobin after infection resolves.",
            "Ask your doctor for iron studies and inflammatory markers (CRP, ESR).",
        ],
    },
    {
        "id": "high_rbc_low_mcv",
        "name": "Thalassemia Trait Pattern",
        "severity": "mild",
        "conditions": [
            {"metric": "rbc", "status": "high"},
            {"metric": "mcv", "status": "low"},
        ],
        "explanation": "A high RBC count with a low MCV (microcytic cells) is a classic pattern for thalassemia trait rather than iron deficiency.",
        "simple_explanation": "You have more red cells than normal but they are smaller. This pattern — high count, small size — is a hallmark of thalassemia trait, which is different from iron deficiency.",
        "possible_causes": [
            "Alpha or beta thalassemia trait (carrier state)",
            "Distinguishing feature from iron deficiency: high RBC vs low RBC",
        ],
        "actions": [
            "Ask for hemoglobin electrophoresis or HPLC to confirm thalassemia trait.",
            "Iron studies are still useful to rule out concurrent iron deficiency.",
            "Thalassemia trait is usually benign — but partners may need screening before family planning.",
            "Genetic counseling may be appropriate if you plan to have children.",
        ],
    },
    {
        "id": "myeloid_stress_pattern",
        "name": "Myeloid Stress Response",
        "severity": "mild",
        "conditions": [
            {"metric": "wbc", "status": "high"},
            {"metric": "neutrophils", "status": "high"},
            {"metric": "platelets", "status": "high"},
        ],
        "explanation": "Elevated WBC, neutrophils, and platelets together suggest a significant reactive bone marrow response.",
        "simple_explanation": "Multiple blood cell types are elevated, which suggests your bone marrow is in a high-production state — often in response to a significant infection, inflammation, or physical stress.",
        "possible_causes": [
            "Severe bacterial infection or sepsis",
            "Major trauma or surgery",
            "Severe inflammation",
            "Corticosteroid use",
        ],
        "actions": [
            "Identify and treat the underlying cause urgently.",
            "Repeat CBC after treatment.",
            "If no clear cause is found, discuss further investigation with your doctor.",
        ],
    },
    {
        "id": "nutritional_deficiency_pattern",
        "name": "Nutritional Deficiency Pattern",
        "severity": "moderate",
        "conditions": [
            {"metric": "hemoglobin", "status": "low"},
            {"metric": "mcv", "status": "high"},
            {"metric": "mch", "status": "high"},
        ],
        "explanation": "Low hemoglobin with high MCV and high MCH is the classic picture of megaloblastic anemia from B12 or folate deficiency.",
        "simple_explanation": "Your red cells are abnormally large and stuffed with hemoglobin but still not enough of them — this is the classic B12 or folate deficiency pattern.",
        "possible_causes": [
            "Vitamin B12 deficiency (vegans, elderly, pernicious anemia)",
            "Folate deficiency (poor diet, pregnancy, alcohol)",
            "Combined B12 and folate deficiency",
        ],
        "actions": [
            "Test serum B12 and RBC folate urgently.",
            "Start supplementation promptly after testing.",
            "B12: eggs, dairy, fish, fortified foods or IM injections if severe.",
            "Folate: leafy greens, legumes, fortified grains.",
            "Review for pernicious anemia (anti-intrinsic factor antibodies).",
        ],
    },
    {
        "id": "hypochromia_pattern",
        "name": "Hypochromia Pattern",
        "severity": "mild",
        "conditions": [
            {"metric": "mch", "status": "low"},
            {"metric": "mchc", "status": "low"},
        ],
        "explanation": "Low MCH and MCHC indicate red cells with less hemoglobin content — pale, under-filled red cells.",
        "simple_explanation": "Your red cells are carrying less hemoglobin than they should — they look paler than normal under a microscope. Iron deficiency is the most common cause.",
        "possible_causes": [
            "Iron deficiency (most common)",
            "Thalassemia",
            "Chronic blood loss",
            "Lead poisoning (rare)",
        ],
        "actions": [
            "Test serum ferritin and iron to confirm iron deficiency.",
            "If iron stores are normal, consider thalassemia screening.",
            "Dietary iron optimization and supplementation as advised.",
        ],
    },

    # ─── LIPID PROFILE ────────────────────────────────────────────────────────
    {
        "id": "atherogenic_dyslipidemia",
        "name": "Atherogenic Dyslipidemia",
        "report_type": "lipid",
        "severity": "significant",
        "conditions": [
            {"metric": "ldl", "status": "high"},
            {"metric": "hdl", "status": "low"},
            {"metric": "triglycerides", "status": "high"},
        ],
        "explanation": "High LDL, low HDL, and high triglycerides together form the classic atherogenic lipid pattern linked to cardiovascular risk.",
        "simple_explanation": "Your 'bad' cholesterol and fats are high while your 'good' cholesterol is low — this combination raises heart disease risk over time.",
        "possible_causes": [
            "Diet high in saturated/trans fats and refined carbohydrates",
            "Sedentary lifestyle",
            "Insulin resistance or metabolic syndrome",
            "Genetic (familial) dyslipidemia",
        ],
        "actions": [
            "Discuss cardiovascular risk assessment with your doctor.",
            "Reduce saturated fat, trans fat, and refined sugar intake.",
            "Increase physical activity and fiber intake.",
            "Ask whether statin or other lipid-lowering therapy is appropriate.",
        ],
    },
    {
        "id": "combined_hyperlipidemia",
        "name": "Combined Hyperlipidemia",
        "report_type": "lipid",
        "severity": "significant",
        "conditions": [
            {"metric": "total_cholesterol", "status": "high"},
            {"metric": "triglycerides", "status": "high"},
        ],
        "explanation": "Elevated total cholesterol together with elevated triglycerides indicates a combined lipid disorder.",
        "simple_explanation": "Both your overall cholesterol and your triglycerides (fat in the blood) are running high.",
        "possible_causes": ["Poor dietary pattern", "Obesity/metabolic syndrome", "Genetic predisposition", "Uncontrolled diabetes"],
        "actions": [
            "Review diet and weight with your doctor.",
            "Consider a repeat fasting lipid profile to confirm.",
            "Screen for diabetes if not already done.",
        ],
    },
    {
        "id": "isolated_ldl_elevation",
        "name": "Isolated LDL Elevation",
        "report_type": "lipid",
        "severity": "moderate",
        "conditions": [{"metric": "ldl", "status": "high"}],
        "explanation": "LDL cholesterol alone is elevated, with other lipid markers in range.",
        "simple_explanation": "Your 'bad' cholesterol (LDL) is a bit high on its own.",
        "possible_causes": ["Dietary cholesterol/saturated fat intake", "Genetic factors", "Early metabolic changes"],
        "actions": ["Discuss target LDL levels with your doctor based on your overall risk.", "Increase soluble fiber intake.", "Repeat testing in 3 months if lifestyle changes are made."],
    },
    {
        "id": "low_hdl_pattern",
        "name": "Low HDL (Cardioprotective Deficiency)",
        "report_type": "lipid",
        "severity": "moderate",
        "conditions": [{"metric": "hdl", "status": "low"}],
        "explanation": "Low HDL reduces the body's reverse cholesterol transport, a known cardiovascular risk factor independent of LDL.",
        "simple_explanation": "Your 'good' cholesterol (HDL), which normally protects your heart, is lower than it should be.",
        "possible_causes": ["Sedentary lifestyle", "Smoking", "Obesity", "Genetic factors"],
        "actions": ["Increase aerobic exercise.", "Stop smoking if applicable.", "Include healthy fats like nuts, olive oil, and fatty fish."],
    },
    {
        "id": "hypertriglyceridemia",
        "name": "Hypertriglyceridemia",
        "report_type": "lipid",
        "severity": "moderate",
        "conditions": [{"metric": "triglycerides", "status": "high"}],
        "explanation": "Elevated triglycerides alone, with cholesterol fractions in range.",
        "simple_explanation": "The fat (triglyceride) level in your blood is higher than normal.",
        "possible_causes": ["High sugar/refined carbohydrate intake", "Alcohol use", "Poorly controlled diabetes", "Obesity"],
        "actions": ["Reduce sugar, refined carbs, and alcohol intake.", "Increase omega-3 rich foods (fish, flaxseed).", "Discuss testing for diabetes if not already screened."],
    },

    # ─── LIVER FUNCTION TEST ─────────────────────────────────────────────────
    {
        "id": "hepatocellular_pattern",
        "name": "Hepatocellular Injury Pattern",
        "report_type": "lft",
        "severity": "significant",
        "conditions": [{"metric": "sgot", "status": "high"}, {"metric": "sgpt", "status": "high"}],
        "explanation": "Both SGOT (AST) and SGPT (ALT) are elevated, suggesting liver cell injury rather than a bile-flow problem.",
        "simple_explanation": "Two key liver enzymes are both raised — this usually points to liver cells being irritated or damaged, from causes like viral hepatitis, fatty liver, or alcohol.",
        "possible_causes": ["Viral hepatitis (A/B/C/E)", "Fatty liver disease (NAFLD)", "Alcohol-related liver injury", "Certain medications or supplements"],
        "actions": [
            "See a doctor to investigate the cause of liver enzyme elevation.",
            "Avoid alcohol until evaluated.",
            "Ask about a liver ultrasound and viral hepatitis screening.",
            "Review current medications/supplements with your doctor.",
        ],
    },
    {
        "id": "cholestatic_pattern",
        "name": "Cholestatic Pattern",
        "report_type": "lft",
        "severity": "significant",
        "conditions": [{"metric": "alp", "status": "high"}, {"metric": "total_bilirubin", "status": "high"}],
        "explanation": "Elevated alkaline phosphatase together with elevated bilirubin suggests impaired bile flow (cholestasis) rather than direct liver cell injury.",
        "simple_explanation": "This pattern suggests bile isn't flowing normally out of the liver, which can happen with gallstones or bile duct blockage.",
        "possible_causes": ["Gallstones or bile duct obstruction", "Cholestatic liver disease", "Certain medications"],
        "actions": ["See a doctor promptly — an abdominal ultrasound is usually the next step.", "Watch for yellowing of eyes/skin, dark urine, or pale stools.", "Avoid alcohol until evaluated."],
    },
    {
        "id": "isolated_hyperbilirubinemia",
        "name": "Isolated Hyperbilirubinemia",
        "report_type": "lft",
        "severity": "moderate",
        "conditions": [{"metric": "total_bilirubin", "status": "high"}],
        "explanation": "Bilirubin is elevated while liver enzymes are otherwise unremarkable.",
        "simple_explanation": "Your bilirubin (the pigment that can cause yellowing) is a bit high, but your liver enzymes look fine — this is often a benign, harmless pattern (like Gilbert's syndrome).",
        "possible_causes": ["Gilbert's syndrome (common, benign)", "Mild hemolysis", "Fasting or dehydration"],
        "actions": ["Mention this to your doctor, especially if you notice yellowing of the eyes.", "Repeat testing after adequate hydration/food intake.", "Usually no treatment needed if isolated and mild."],
    },
    {
        "id": "hypoalbuminemia",
        "name": "Low Albumin",
        "report_type": "lft",
        "severity": "moderate",
        "conditions": [{"metric": "albumin", "status": "low"}],
        "explanation": "Low serum albumin can reflect chronic liver disease, malnutrition, kidney protein loss, or chronic inflammation.",
        "simple_explanation": "One of your key blood proteins (albumin) is lower than normal — this can relate to the liver, nutrition, kidneys, or ongoing inflammation.",
        "possible_causes": ["Chronic liver disease", "Poor nutrition/protein intake", "Kidney protein loss", "Chronic inflammatory illness"],
        "actions": ["Discuss with your doctor to identify the underlying cause.", "Ensure adequate dietary protein intake.", "Ask whether kidney function should also be checked."],
    },
    {
        "id": "mild_alt_elevation",
        "name": "Mild ALT Elevation",
        "report_type": "lft",
        "severity": "mild",
        "conditions": [{"metric": "sgpt", "status": "high"}],
        "explanation": "SGPT (ALT) alone is mildly elevated, a common and often benign finding.",
        "simple_explanation": "One liver enzyme is a little high on its own — very common, and often related to diet, weight, or mild fatty liver.",
        "possible_causes": ["Fatty liver (often diet/weight related)", "Recent alcohol intake", "Medication effect"],
        "actions": ["Reduce alcohol and processed food intake.", "Maintain a healthy weight and regular activity.", "Repeat testing in a few weeks if this is a first occurrence."],
    },

    # ─── KIDNEY FUNCTION TEST ────────────────────────────────────────────────
    {
        "id": "renal_impairment_pattern",
        "name": "Possible Renal Impairment",
        "report_type": "kft",
        "severity": "significant",
        "conditions": [{"metric": "creatinine", "status": "high"}, {"metric": "blood_urea", "status": "high"}],
        "explanation": "Both creatinine and blood urea are elevated, suggesting reduced kidney filtration.",
        "simple_explanation": "Two key kidney markers are both raised, suggesting your kidneys may not be filtering waste as efficiently as usual.",
        "possible_causes": ["Chronic kidney disease", "Dehydration (acute, reversible)", "Uncontrolled diabetes or hypertension", "Certain medications (NSAIDs, some antibiotics)"],
        "actions": [
            "See a doctor promptly for further kidney function evaluation.",
            "Stay well hydrated unless advised otherwise.",
            "Avoid NSAIDs (like ibuprofen) until evaluated.",
            "Review blood pressure and blood sugar control.",
        ],
    },
    {
        "id": "isolated_urea_elevation",
        "name": "Isolated Urea Elevation",
        "report_type": "kft",
        "severity": "mild",
        "conditions": [{"metric": "blood_urea", "status": "high"}],
        "explanation": "Urea alone is elevated while creatinine is normal — often reflects dehydration, diet, or protein intake rather than kidney disease.",
        "simple_explanation": "Your urea is a bit high on its own — this is frequently just from dehydration or a high-protein meal rather than a kidney problem.",
        "possible_causes": ["Dehydration", "High protein diet", "Recent strenuous exercise"],
        "actions": ["Increase water intake and retest.", "Moderate protein intake before repeat testing.", "Mention to your doctor if it persists."],
    },
    {
        "id": "hyperuricemia",
        "name": "Hyperuricemia",
        "report_type": "kft",
        "severity": "moderate",
        "conditions": [{"metric": "uric_acid", "status": "high"}],
        "explanation": "Elevated uric acid can predispose to gout and, over time, kidney stones.",
        "simple_explanation": "Your uric acid level is high, which raises the risk of gout (joint pain/swelling) and kidney stones.",
        "possible_causes": ["Diet high in purines (red meat, seafood, alcohol)", "Obesity", "Genetic predisposition", "Certain medications (diuretics)"],
        "actions": ["Reduce red meat, organ meat, seafood, and alcohol intake.", "Increase water intake.", "See a doctor if you notice joint pain or swelling."],
    },
    {
        "id": "hyperkalemia",
        "name": "Hyperkalemia",
        "report_type": "kft",
        "severity": "significant",
        "conditions": [{"metric": "potassium", "status": "high"}],
        "explanation": "Elevated potassium can affect heart rhythm and requires prompt attention, especially if markedly high.",
        "simple_explanation": "Your potassium level is high, which can affect your heart rhythm — this should be discussed with a doctor promptly.",
        "possible_causes": ["Kidney dysfunction", "Certain medications (ACE inhibitors, potassium-sparing diuretics)", "Sample handling artifact (hemolysis) — often needs a repeat test"],
        "actions": ["Contact your doctor promptly, especially if markedly elevated.", "Ask whether a repeat test is needed to rule out a lab artifact.", "Review medications that affect potassium with your doctor."],
    },
    {
        "id": "hypokalemia",
        "name": "Hypokalemia",
        "report_type": "kft",
        "severity": "moderate",
        "conditions": [{"metric": "potassium", "status": "low"}],
        "explanation": "Low potassium can cause muscle weakness and, if severe, affect heart rhythm.",
        "simple_explanation": "Your potassium is lower than normal, which can cause weakness or cramps and, if very low, affect the heart.",
        "possible_causes": ["Diuretic use", "Vomiting or diarrhea", "Inadequate dietary intake"],
        "actions": ["Discuss with your doctor, especially if on diuretics.", "Include potassium-rich foods like bananas, coconut water, and leafy greens.", "Seek care urgently if you have palpitations or severe weakness."],
    },
    {
        "id": "hyponatremia",
        "name": "Hyponatremia",
        "report_type": "kft",
        "severity": "moderate",
        "conditions": [{"metric": "sodium", "status": "low"}],
        "explanation": "Low sodium can reflect fluid imbalance and may cause confusion or lethargy if significant.",
        "simple_explanation": "Your sodium level is a bit low, which can be related to how much fluid your body is holding.",
        "possible_causes": ["Excess fluid intake", "Certain medications (diuretics)", "Hormonal imbalance", "Vomiting/diarrhea"],
        "actions": ["Discuss with your doctor, especially with symptoms like confusion or severe headache.", "Review medications that may affect sodium.", "Avoid excessive plain water intake until reviewed."],
    },

    # ─── THYROID PANEL ───────────────────────────────────────────────────────
    {
        "id": "primary_hypothyroidism",
        "name": "Primary Hypothyroidism Pattern",
        "report_type": "thyroid",
        "severity": "significant",
        "conditions": [{"metric": "tsh", "status": "high"}, {"metric": "t4", "status": "low"}],
        "explanation": "High TSH with low T4 is the classic pattern of an underactive thyroid gland.",
        "simple_explanation": "Your thyroid gland appears underactive — your brain is signaling it to work harder (high TSH) but thyroid hormone (T4) is still low.",
        "possible_causes": ["Hashimoto's thyroiditis (autoimmune)", "Iodine deficiency", "Post-treatment for hyperthyroidism", "Certain medications"],
        "actions": ["See a doctor to discuss starting or adjusting thyroid hormone replacement.", "Ask about thyroid antibody testing (anti-TPO).", "Watch for fatigue, weight gain, cold intolerance, and hair thinning."],
    },
    {
        "id": "subclinical_hypothyroidism",
        "name": "Subclinical Hypothyroidism",
        "report_type": "thyroid",
        "severity": "mild",
        "conditions": [{"metric": "tsh", "status": "high"}, {"metric": "t4", "status": "normal"}],
        "explanation": "TSH is elevated but T4 remains within range — an early or mild thyroid underactivity pattern.",
        "simple_explanation": "Your thyroid-stimulating hormone is a bit high, but your actual thyroid hormone level is still normal — an early sign worth monitoring.",
        "possible_causes": ["Early Hashimoto's thyroiditis", "Transient thyroiditis", "Lab variation"],
        "actions": ["Repeat TSH testing in 6-8 weeks.", "Ask about thyroid antibody testing.", "Monitor for symptoms like fatigue or weight changes."],
    },
    {
        "id": "primary_hyperthyroidism",
        "name": "Primary Hyperthyroidism Pattern",
        "report_type": "thyroid",
        "severity": "significant",
        "conditions": [{"metric": "tsh", "status": "low"}, {"metric": "t4", "status": "high"}],
        "explanation": "Low TSH with high T4 is the classic pattern of an overactive thyroid gland.",
        "simple_explanation": "Your thyroid appears overactive — it's producing too much hormone, which is why your brain has dialed back its signal (low TSH).",
        "possible_causes": ["Graves' disease (autoimmune)", "Toxic nodular goiter", "Thyroiditis (early phase)"],
        "actions": ["See a doctor promptly to evaluate the cause.", "Watch for palpitations, weight loss, heat intolerance, and tremor.", "Ask about thyroid antibody and radioactive iodine uptake testing."],
    },
    {
        "id": "subclinical_hyperthyroidism",
        "name": "Subclinical Hyperthyroidism",
        "report_type": "thyroid",
        "severity": "mild",
        "conditions": [{"metric": "tsh", "status": "low"}, {"metric": "t4", "status": "normal"}],
        "explanation": "TSH is suppressed but T4 remains within range — a mild or early overactive thyroid pattern.",
        "simple_explanation": "Your TSH is lower than normal, but your thyroid hormone level itself is still in range — worth monitoring, especially if you have symptoms.",
        "possible_causes": ["Early Graves' disease", "Toxic nodule", "Excess thyroid medication if on treatment"],
        "actions": ["Repeat testing in 6-8 weeks.", "Watch for palpitations, anxiety, or weight loss.", "Review any thyroid medication dosage with your doctor."],
    },

    # ─── BLOOD SUGAR / DIABETES PROFILE ──────────────────────────────────────
    {
        "id": "diabetes_pattern",
        "name": "Diabetes Mellitus Pattern",
        "report_type": "blood_sugar",
        "severity": "significant",
        "conditions": [{"metric": "fasting_sugar", "status": "high"}, {"metric": "hba1c", "status": "high"}],
        "explanation": "Both fasting glucose and HbA1c (3-month average) are elevated, consistent with diabetes mellitus.",
        "simple_explanation": "Your fasting sugar and your 3-month average sugar (HbA1c) are both high — this pattern is consistent with diabetes.",
        "possible_causes": ["Type 2 diabetes", "Type 1 diabetes (especially in younger patients)", "Steroid or other medication-induced hyperglycemia"],
        "actions": [
            "See a doctor promptly to confirm diagnosis and discuss management.",
            "Begin monitoring diet, particularly refined carbohydrates and sugar.",
            "Increase physical activity as advised.",
            "Ask about additional testing (OGTT, C-peptide) if the picture is unclear.",
        ],
    },
    {
        "id": "prediabetes_pattern",
        "name": "Impaired Fasting Glucose (Prediabetes Pattern)",
        "report_type": "blood_sugar",
        "severity": "moderate",
        "conditions": [{"metric": "fasting_sugar", "status": "high"}, {"metric": "hba1c", "status": "normal"}],
        "explanation": "Fasting glucose is elevated while HbA1c remains in range — an early, often reversible pattern worth acting on.",
        "simple_explanation": "Your fasting sugar is a bit high today, but your 3-month average is still normal — this is an early warning sign, not yet diabetes.",
        "possible_causes": ["Early insulin resistance", "Recent dietary intake affecting fasting result", "Stress or illness"],
        "actions": ["Repeat fasting glucose testing to confirm.", "Reduce refined carbohydrate and sugar intake.", "Increase physical activity.", "Recheck HbA1c in 3 months."],
    },
    {
        "id": "elevated_hba1c",
        "name": "Elevated HbA1c",
        "report_type": "blood_sugar",
        "severity": "moderate",
        "conditions": [{"metric": "hba1c", "status": "high"}],
        "explanation": "HbA1c, reflecting average blood sugar over the past ~3 months, is elevated on its own.",
        "simple_explanation": "Your average blood sugar over the last few months is running a bit high.",
        "possible_causes": ["Prediabetes or early diabetes", "Dietary pattern high in sugar/refined carbs", "Reduced physical activity"],
        "actions": ["Discuss with your doctor whether further testing (fasting glucose, OGTT) is needed.", "Adopt a lower-glycemic diet.", "Increase regular physical activity."],
    },
    {
        "id": "hypoglycemia_pattern",
        "name": "Hypoglycemia",
        "report_type": "blood_sugar",
        "severity": "significant",
        "conditions": [{"metric": "fasting_sugar", "status": "low"}],
        "explanation": "Fasting blood sugar is below the normal range, which can cause symptoms and needs prompt attention.",
        "simple_explanation": "Your fasting blood sugar is lower than normal — this can cause shakiness, sweating, or confusion and should be discussed with a doctor.",
        "possible_causes": ["Prolonged fasting before the test", "Diabetes medication (if applicable)", "Reactive hypoglycemia", "Rare: insulin-producing tumor"],
        "actions": ["If you feel shaky, sweaty, or confused now, eat or drink something with sugar immediately.", "Discuss with your doctor, especially if you're on diabetes medication.", "Avoid prolonged fasting before repeat testing."],
    },
    {
        "id": "elevated_postprandial",
        "name": "Elevated Postprandial Glucose",
        "report_type": "blood_sugar",
        "severity": "moderate",
        "conditions": [{"metric": "pp_sugar", "status": "high"}],
        "explanation": "Post-meal glucose is elevated, which can be an early marker of impaired glucose tolerance even before fasting levels rise.",
        "simple_explanation": "Your blood sugar after eating is higher than it should be — sometimes this shows up before fasting sugar does.",
        "possible_causes": ["Early insulin resistance", "High-carbohydrate meal before testing", "Prediabetes"],
        "actions": ["Reduce portion sizes of refined carbohydrates.", "Take a short walk after meals.", "Discuss HbA1c or OGTT testing with your doctor."],
    },
]